[workspace]
resolver = "2"
members = ["day-*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
regex = "1.10.2"
lazy_static = "1.4.0"
num = "0.4.1"